Repository CZERTAINLY/CZERTAINLY-Helm-Charts, pull requests merged in 2023-12, with the labels that each got.

#159 Create develop 0.0.0 tag for development charts in workflow
  .github/workflows/release_develop.yml
Labels: ignore-for-release

#158 startup/readines probes tuning
  charts/api-gateway-kong/Chart.yaml
  charts/api-gateway-kong/README.md
  charts/api-gateway-kong/values.yaml
  charts/auth-opa-policies/Chart.yaml
  charts/auth-opa-policies/README.md
  charts/auth-opa-policies/values.yaml
  charts/auth-service/Chart.yaml
  charts/auth-service/README.md
  charts/auth-service/values.yaml
  charts/common-credential-provider/Chart.yaml
  charts/common-credential-provider/README.md
  charts/common-credential-provider/values.yaml
  charts/cryptosense-discovery-provider/Chart.yaml
  charts/cryptosense-discovery-provider/README.md
  charts/cryptosense-discovery-provider/values.yaml
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
  charts/czertainly/docs/configurable-parameters.md
  charts/czertainly/values.yaml
  charts/ejbca-ng-connector/Chart.yaml
  charts/ejbca-ng-connector/README.md
  charts/ejbca-ng-connector/values.yaml
  charts/email-notification-provider/Chart.yaml
  charts/email-notification-provider/README.md
  charts/email-notification-provider/values.yaml
  charts/fe-administrator/Chart.yaml
  charts/fe-administrator/README.md
  charts/fe-administrator/values.yaml
  charts/keycloak-internal/Chart.yaml
  charts/keycloak-internal/README.md
  charts/keycloak-internal/values.yaml
  charts/keystore-entity-provider/Chart.yaml
  charts/keystore-entity-provider/README.md
  charts/keystore-entity-provider/values.yaml
  charts/messaging-rabbitmq/Chart.yaml
  charts/messaging-rabbitmq/README.md
  charts/messaging-rabbitmq/values.yaml
  charts/ms-adcs-connector/Chart.yaml
  charts/ms-adcs-connector/README.md
  charts/ms-adcs-connector/values.yaml
  charts/network-discovery-provider/Chart.yaml
  charts/network-discovery-provider/README.md
  charts/network-discovery-provider/values.yaml
  charts/scheduler-service/Chart.lock
  charts/scheduler-service/Chart.yaml
  charts/scheduler-service/README.md
  charts/scheduler-service/values.yaml
  charts/software-cryptography-provider/Chart.yaml
  charts/software-cryptography-provider/README.md
  charts/software-cryptography-provider/values.yaml
  charts/utils-service/Chart.yaml
  charts/utils-service/README.md
  charts/utils-service/values.yaml
  charts/x509-compliance-provider/Chart.yaml
  charts/x509-compliance-provider/README.md
  charts/x509-compliance-provider/values.yaml
  update-all-dependencies.sh
Labels: workflow-approved

#160 Add adcs-net-connector chart
  README.md
  charts/adcs-net-connector/.helmignore
  charts/adcs-net-connector/Chart.lock
  charts/adcs-net-connector/Chart.yaml
  charts/adcs-net-connector/README.md
  charts/adcs-net-connector/ci/develop-values.yaml
  charts/adcs-net-connector/templates/NOTES.txt
  charts/adcs-net-connector/templates/_helpers.tpl
  charts/adcs-net-connector/templates/adcs-net-connector-deployment.yaml
  charts/adcs-net-connector/templates/adcs-net-connector-secret.yaml
  charts/adcs-net-connector/templates/adcs-net-connector-service.yaml
  charts/adcs-net-connector/templates/tests/test-connection.yaml
  charts/adcs-net-connector/templates/trusted-certificates-secret.yaml
  charts/adcs-net-connector/values.yaml
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
  charts/czertainly/docs/configurable-parameters.md
  charts/czertainly/docs/upgrading.md
  charts/czertainly/values.yaml
  update-all-dependencies.sh
Labels: new-feature, workflow-approved
