Repository CZERTAINLY/CZERTAINLY-Helm-Charts, pull requests merged in 2024-02, with the labels that each got.

#164 Register pyAdcsConnector to the install job
  charts/czertainly/templates/hooks/register-connectors-job.yaml
Labels: bug, ignore-for-release, workflow-approved

#165 Update release version to 2.11.0
  charts/api-gateway-kong/Chart.yaml
  charts/auth-opa-policies/Chart.yaml
  charts/auth-service/Chart.yaml
  charts/common-credential-provider/Chart.yaml
  charts/cryptosense-discovery-provider/Chart.yaml
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
  charts/czertainly/docs/configurable-parameters.md
  charts/czertainly/docs/overview.md
  charts/czertainly/values.yaml
  charts/ejbca-ng-connector/Chart.yaml
  charts/ejbca-ng-connector/README.md
  charts/ejbca-ng-connector/values.yaml
  charts/email-notification-provider/Chart.yaml
  charts/fe-administrator/Chart.yaml
  charts/fe-administrator/README.md
  charts/fe-administrator/values.yaml
  charts/keycloak-internal/Chart.yaml
  charts/keystore-entity-provider/Chart.yaml
  charts/messaging-rabbitmq/Chart.yaml
  charts/ms-adcs-connector/Chart.yaml
  charts/network-discovery-provider/Chart.yaml
  charts/pyadcs-connector/Chart.yaml
  charts/pyadcs-connector/ci/develop-values.yaml
  charts/scheduler-service/Chart.lock
  charts/scheduler-service/Chart.yaml
  charts/software-cryptography-provider/Chart.yaml
  charts/utils-service/Chart.yaml
  charts/x509-compliance-provider/Chart.yaml
Labels: ignore-for-release, skip-workflow

#168 Update version of api-gateway-kong image
  charts/api-gateway-kong/Chart.yaml
  charts/api-gateway-kong/README.md
  charts/api-gateway-kong/values.yaml
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
Labels: enhancement, workflow-approved

#171 create keycloak schema on start if it doesn't exists
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
  charts/keycloak-internal/Chart.yaml
  charts/keycloak-internal/README.md
  charts/keycloak-internal/templates/keycloak-internal-deployment.yaml
  charts/keycloak-internal/templates/keycloak-internal-secret.yaml
  charts/keycloak-internal/values.yaml
Labels: enhancement, workflow-approved
