Repository CZERTAINLY/CZERTAINLY-Helm-Charts, pull requests merged in 2024-12, with the labels that each got.

#209 Update audit logging information
  charts/czertainly/docs/configurable-parameters.md
  charts/czertainly/docs/upgrading.md
  charts/czertainly/templates/core-deployment.yaml
  charts/czertainly/values.yaml
Labels: enhancement, workflow-approved

#207 Add /opt/keycloak/.keycloak mount to use CLI
  charts/keycloak-internal/templates/keycloak-internal-deployment.yaml
Labels: enhancement, workflow-approved

#210 Update default registry of pyadcs-connector to docker.io
  charts/pyadcs-connector/values.yaml
Labels: bug, workflow-approved

#211 Update 2.14.0 upgrading documentation
  charts/api-gateway-kong/README.md
  charts/api-gateway-kong/values.yaml
  charts/czertainly/docs/upgrading.md
Labels: documentation, workflow-approved

#213 Updates for release 2.14.0
  charts/api-gateway-kong/Chart.lock
  charts/api-gateway-kong/Chart.yaml
  charts/auth-opa-policies/Chart.lock
  charts/auth-opa-policies/Chart.yaml
  charts/auth-service/Chart.lock
  charts/auth-service/Chart.yaml
  charts/auth-service/README.md
  charts/auth-service/values.yaml
  charts/common-credential-provider/Chart.lock
  charts/common-credential-provider/Chart.yaml
  charts/cryptosense-discovery-provider/Chart.lock
  charts/cryptosense-discovery-provider/Chart.yaml
  charts/ct-logs-discovery-provider/Chart.lock
  charts/ct-logs-discovery-provider/Chart.yaml
  charts/czertainly-lib/Chart.yaml
  charts/czertainly/Chart.lock
  charts/czertainly/Chart.yaml
  charts/czertainly/docs/configurable-parameters.md
  charts/czertainly/values.yaml
  charts/ejbca-ng-connector/Chart.lock
  charts/ejbca-ng-connector/Chart.yaml
  charts/email-notification-provider/Chart.lock
  charts/email-notification-provider/Chart.yaml
  charts/fe-administrator/Chart.lock
  charts/fe-administrator/Chart.yaml
  charts/fe-administrator/README.md
  charts/fe-administrator/values.yaml
  charts/hashicorp-vault-connector/Chart.lock
  charts/hashicorp-vault-connector/Chart.yaml
  charts/keycloak-internal/Chart.lock
  charts/keycloak-internal/Chart.yaml
  charts/keystore-entity-provider/Chart.lock
  charts/keystore-entity-provider/Chart.yaml
  charts/messaging-rabbitmq/Chart.lock
  charts/messaging-rabbitmq/Chart.yaml
  charts/network-discovery-provider/Chart.lock
  charts/network-discovery-provider/Chart.yaml
  charts/network-discovery-provider/README.md
  charts/network-discovery-provider/values.yaml
  charts/pyadcs-connector/Chart.lock
  charts/pyadcs-connector/Chart.yaml
  charts/scheduler-service/Chart.lock
  charts/scheduler-service/Chart.yaml
  charts/software-cryptography-provider/Chart.lock
  charts/software-cryptography-provider/Chart.yaml
  charts/utils-service/Chart.lock
  charts/utils-service/Chart.yaml
  charts/x509-compliance-provider/Chart.lock
  charts/x509-compliance-provider/Chart.yaml
Labels: ignore-for-release, skip-workflow
